### ISSUE TITLE
"tf_synthesizer.cc"

### ISSUE THREAD

**Issue by plutols** [syoyo/tacotron-tts-cpp#2]
when I run make,there is a error,
 Scanning dependencies of target tts
[ 25%] Building CXX object CMakeFiles/tts.dir/src/main.cc.o
[ 50%] Building CXX object CMakeFiles/tts.dir/src/tf_synthesizer.cc.o
[ 75%] Building CXX object CMakeFiles/tts.dir/src/audio_util.cc.o
[100%] Linking CXX executable tts
/usr/bin/ld: CMakeFiles/tts.dir/src/tf_synthesizer.cc.o: undefined reference to symbol '_ZN10tensorflow6TensorC1ENS_8DataTypeERKNS_11TensorShapeE'
/home/aiken/tensorflow/bazel-bin/tensorflow/libtensorflow_framework.so: error adding symbols: DSO missing from command line
can you know what's problem about this

**Comment by syoyo** [comment]
It looks some libtensorflow .so files are missing at linking.

`--config=monolithic` may solve the issue(I use monolithic build of libtensorflow_cc.so)

https://www.tensorflow.org/install/source#preconfigured_configurations

**Comment by plutols** [comment]
ok,thanks it works
I generate my libtensorflow_cc.so by using two command:
&nbsp; &nbsp; &nbsp;&nbsp;bazel build --config=monolithic --config=cuda //tensorflow:libtensorflow_cc.so
&nbsp; &nbsp; &nbsp; bazel build --config=monolithic --config=cuda //tensorflow:libtensorflow_framework.soit is better than one command --bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Syoyo Fujita"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月16日(星期三) 晚上6:51
收件人:&nbsp;"syoyo/tacotron-tts-cpp"<tacotron-tts-cpp@noreply.github.com&gt;;
抄送:&nbsp;"叶世晴"<1550046878@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [syoyo/tacotron-tts-cpp] "tf_synthesizer.cc" (#2)




It looks some libtensorflow .so files are missing at linking.
 
--config=monolithic may solve the issue(I use monolithic build of libtensorflow_cc.so)
 
https://www.tensorflow.org/install/source#preconfigured_configurations

**Comment by plutols** [comment]
it's solved,
I generate my libtensorflow_cc.so by using two command:
      bazel build --config=monolithic --config=cuda //tensorflow:libtensorflow_cc.so
      bazel build --config=monolithic --config=cuda //tensorflow:libtensorflow_framework.so
it is better than one command --bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so

**Comment by syoyo** [comment]
Good.

BTW, we are migrating to use TF C API, which will reduce linking problems and would run various platforms including Android. You can try it with `android` branch: https://github.com/syoyo/tacotron-tts-cpp/tree/android

**Comment by plutols** [comment]
ok,thank you , I got it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Syoyo Fujita"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 中午1:21
收件人: "syoyo/tacotron-tts-cpp"<tacotron-tts-cpp@noreply.github.com&gt;; 
抄送: "叶世晴"<1550046878@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [syoyo/tacotron-tts-cpp] &quot;tf_synthesizer.cc&quot; (#2)




Good.
 
BTW, we are migrating to use TF C API, which will reduce linking problems and would run various platforms including Android. You can try it with android branch: https://github.com/syoyo/tacotron-tts-cpp/tree/android

**Comment by syoyo** [comment]
I think you got a succes to build the app so this issue would be ready to close.

**Comment by plutols** [comment]
it's ok ,thanks for sharing



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Syoyo Fujita"<notifications@github.com&gt;; 
发送时间: 2019年10月26日(星期六) 晚上11:53
收件人: "syoyo/tacotron-tts-cpp"<tacotron-tts-cpp@noreply.github.com&gt;; 
抄送: "叶世晴"<1550046878@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [syoyo/tacotron-tts-cpp] &quot;tf_synthesizer.cc&quot; (#2)




I think you got a succes to build the app so this issue would be ready to close.
