### ISSUE TITLE
how can get mode.pb?

### ISSUE THREAD

**Issue by YoLi-sw** [syoyo/tacotron-tts-cpp#4]
I have noticed that you have got a very good frozen model. How do you do it?
I got the model.ckpt  through training, but I couldn't transfer out the Pb file. Looking forward to your reply.

**Comment by syoyo** [comment]
Procedure is described in README.

https://github.com/syoyo/tacotron-tts-cpp#dump-graph

**Comment by YoLi-sw** [comment]
Thank you very much!! 
I get the model.pb now.
I have another question， when I freeze_graph ,how can I get the output_node_names? 
Because I use another git, I'm not sure what the last node is. :(
[https://github.com/begeekmyfriend/Tacotron-2](https://github.com/begeekmyfriend/Tacotron-2)

**Comment by syoyo** [comment]
>  when I freeze_graph ,how can I get the output_node_names?

https://github.com/lutzroeder/netron

You can use Netron to find output nodes.

**Comment by YoLi-sw** [comment]
Thank you very much for your reply. I'll try again
